-- 04 recipes (generated by the AI edge functions via service role), saves, cooking history.

create table public.recipes (
  id              uuid primary key default gen_random_uuid(),
  household_id    uuid references public.households (id) on delete cascade,
  title           text not null,
  summary         text not null default '',
  time_active_min int not null default 15,
  time_total_min  int not null default 25,
  servings        int not null default 2,
  kcal            int,
  tags            text[] not null default '{}',
  ingredients     jsonb not null default '[]',
  steps           jsonb not null default '[]',
  uses_item_ids   uuid[] not null default '{}',
  missing         jsonb not null default '[]',
  est_cost_eur    numeric,
  image_url       text,
  image_is_ai     boolean not null default true,
  source          text not null default 'ai',
  created_by      uuid references auth.users (id) on delete set null,
  created_at      timestamptz not null default now(),
  constraint recipes_source_chk check (source in ('ai','import','family'))
);
create index recipes_household_idx on public.recipes (household_id, created_at desc);

create table public.recipe_saves (
  user_id    uuid not null references auth.users (id) on delete cascade,
  recipe_id  uuid not null references public.recipes (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, recipe_id)
);

create table public.meal_history (
  id            uuid primary key default gen_random_uuid(),
  household_id  uuid not null references public.households (id) on delete cascade,
  recipe_id     uuid references public.recipes (id) on delete set null,
  recipe_title  text not null,
  cooked_on     date not null default current_date,
  cooked_by     uuid references auth.users (id) on delete set null,
  rating        text,
  feedback      text[] not null default '{}',
  notes         text,
  user_photo_url text,
  constraint meal_rating_chk check (rating is null or rating in ('love','ok','never'))
);
create index meal_history_household_idx on public.meal_history (household_id, cooked_on desc);

create or replace function public.get_recipe(p_recipe uuid) returns jsonb
language plpgsql security definer set search_path = public as $$
declare r recipes;
begin
  select * into r from recipes where id = p_recipe;
  if not found then raise exception 'not_found'; end if;
  if r.household_id is not null then perform private.require_member(r.household_id); end if;
  return to_jsonb(r);
end $$;

create or replace function public.get_recipes(p_household uuid, p_filter text default 'recent') returns jsonb
language plpgsql security definer set search_path = public as $$
declare out jsonb;
begin
  perform private.require_member(p_household);
  if p_filter = 'saved' then
    select coalesce(jsonb_agg(to_jsonb(r) order by s.created_at desc), '[]') into out
    from recipe_saves s join recipes r on r.id = s.recipe_id
    where s.user_id = auth.uid() and (r.household_id = p_household or r.household_id is null);
  elsif p_filter = 'favourites' then
    select coalesce(jsonb_agg(to_jsonb(r) order by r.created_at desc), '[]') into out
    from recipes r
    where r.household_id = p_household
      and exists (select 1 from meal_history h where h.recipe_id = r.id and h.rating = 'love');
  else
    select coalesce(jsonb_agg(to_jsonb(r) order by r.created_at desc), '[]') into out
    from (select * from recipes where household_id = p_household order by created_at desc limit 50) r;
  end if;
  return out;
end $$;

create or replace function public.save_recipe(p_recipe uuid, p_saved boolean default true) returns void
language plpgsql security definer set search_path = public as $$
declare hid uuid;
begin
  if auth.uid() is null then raise exception 'sign_in_required'; end if;
  select household_id into hid from recipes where id = p_recipe;
  if hid is not null then perform private.require_member(hid); end if;
  if p_saved then
    insert into recipe_saves (user_id, recipe_id) values (auth.uid(), p_recipe) on conflict do nothing;
  else
    delete from recipe_saves where user_id = auth.uid() and recipe_id = p_recipe;
  end if;
end $$;

create or replace function public.rate_meal(p_recipe uuid, p_rating text, p_feedback text[] default '{}', p_notes text default null)
returns jsonb language plpgsql security definer set search_path = public as $$
declare r recipes; h meal_history;
begin
  select * into r from recipes where id = p_recipe;
  if not found then raise exception 'not_found'; end if;
  if r.household_id is null then raise exception 'not_member'; end if;
  perform private.require_member(r.household_id);
  if p_rating not in ('love','ok','never') then raise exception 'rating_invalid'; end if;
  insert into meal_history (household_id, recipe_id, recipe_title, cooked_by, rating, feedback, notes)
  values (r.household_id, r.id, r.title, auth.uid(), p_rating, coalesce(p_feedback, '{}'), nullif(trim(coalesce(p_notes,'')), ''))
  returning * into h;
  return to_jsonb(h);
end $$;

create or replace function public.get_history(p_household uuid) returns jsonb
language plpgsql security definer set search_path = public as $$
begin
  perform private.require_member(p_household);
  return (select coalesce(jsonb_agg(to_jsonb(h) order by h.cooked_on desc, h.id desc), '[]')
          from meal_history h where h.household_id = p_household);
end $$;
